version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  target-branch: dependancies
  labels:
  - ruby
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.0
    - 3.12.1
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: dry-types
    versions:
    - 1.5.0
  - dependency-name: dry-configurable
    versions:
    - 0.12.0
  - dependency-name: rollbar
    versions:
    - 3.1.1
  - dependency-name: grape-entity
    versions:
    - 0.8.2
  - dependency-name: groupdate
    versions:
    - 5.2.1
  - dependency-name: kramdown
    versions:
    - 2.3.0
  - dependency-name: carrierwave
    versions:
    - 2.1.0
  - dependency-name: oauth2
    versions:
    - 1.4.4
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  target-branch: dependancies
  labels:
  - javascript
  ignore:
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: vue-turbolinks
    versions:
    - 2.2.1
  - dependency-name: "@rails/webpacker"
    versions:
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
