language: ruby
dist: trusty
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database placecal_test;' -U postgres
before_install:
- openssl aes-256-cbc -K $encrypted_f4f309cbfdaf_key -iv $encrypted_f4f309cbfdaf_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan placecal.org >> ~/.ssh/known_hosts
- git remote add deploy dokku@placecal.org:placecal
- git config --global push.default simple
- git push deploy master
